# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: CI GitHub workflow

on: 
  push:
   branches: [ "release-*" ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile --file artifact2/pom.xml 

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Run Tests with Maven
      run: mvn -B test --file artifact2/pom.xml 
    - name: ServiceNow DevOps Unit Test Results
      uses: ServiceNow/servicenow-devops-test-report@v3.0.0
      with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Test'
          xml-report-filename: artifact2/target/surefire-reports/testng-results.xml
          
  registerartifact:
    name: Register Artifact
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Extract Version
      run: |
          version=$(sed -n 's,.*<version>\(.*\)</version>.*,\1,p' artifact2/pom.xml | head -1)
          echo " Version extrated from pom.xml: $version"
          name=$(sed -n 's,.*<artifactId>\(.*\)</artifactId.*,\1,p' artifact2/pom.xml | head -1)
          echo " artifactid extrated from artifact2/pom.xml: $name"
          echo "artifactid=$(echo $name)"  >> "$GITHUB_ENV"
          echo "pomversion=$(echo $version)" >> "$GITHUB_ENV"
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          sha=$(git rev-parse --short "$GITHUB_SHA")
          echo $sha
          touch $sha
          artifact=$name-$(git rev-parse --short "$GITHUB_SHA").jar
          echo "artifact details are $artifact"
          echo "artifact:$artifact" > $(echo $name)-$(echo $version )
          echo "version:$(echo $version)"  >> $(echo $name)-$(echo $version )
          echo "semanticVersion:$(echo $version)" >> $(echo $name)-$(echo $version )
          echo "repo:${{ github.repository }}" >> $(echo $name)-$(echo $version )
          

          
          
    - name: ServiceNow Register Artifact
      uses: ServiceNow/servicenow-devops-register-artifact@v2.0.0
      with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Register Artifact'
          artifacts: '[{"name": "${{ env.artifactid }}-${{ env.sha_short }}.jar","version": "${{ env.pomversion}}","semanticVersion": "${{ env.pomversion}}","repositoryName": "${{ github.repository }}"}]'

    - name: Push to Build Registry
      uses: dmnemec/copy_file_to_another_repo_action@main
      env: 
        API_TOKEN_GITHUB: ${{ secrets.Build_REPO_PERSONAL_ACCESS_TOKEN }}   
      with:
        # GitHub Action output files
        source_file: '${{ env.artifactid }}-${{ env.pomversion}}'
      #  source_file: '$artifact'
        user_name: 'ArunKumarReddy407'
        destination_repo: 'ArunKumarReddy407/buildmetadata'
        destination_folder: 'release/app2/'
        #user-email: <your email>
        # It defaults to `main`
        #target-branch: "main"
        commit_message: 'Push artifact2 to Build registry repo'
  deploytotest:
    name: 'DeploytoTest'
    needs: registerartifact
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment scripts
      run: echo 'Deployment step in progress...'
